spring:
  elasticsearch:
    uris: http://elasticsearch:9200
    username: elastic
    password: password
    connection-timeout: 5s
    socket-timeout: 60s
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

elasticsearch:
  index:
    name: logs

