server:
  port: 8025
  # Elasticsearch Configuration
spring:
  application:
    name: loggingservice
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: password
    connection-timeout: 5s
    socket-timeout: 60s

  # Elasticsearch Index Configuration
elasticsearch:
  index:
    name: logs