server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: taskRouteApplication

rabbitmq:
  host: localhost
  port: 5672
  exchange:
    message: message.exchange
    logs: logs.exchange

router:
  publish-retry:
    attempts: 3
    backoff-ms: 500